apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: a4xu361c3-python 
  janus-idp.io/tekton: a4xu361c3-python
  backstage.io/kubernetes-id: a4xu361c3-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: a4xu361c3-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml